# Buzera Tiberiu <tiberiu.buzera@stud.acs.upb.ro>

build:
	g++ poduri.cpp -o poduri
	g++ adrese.cpp -o adrese
	g++ lego.cpp -o lego
	g++ retea.cpp -o retea

run-p1:
	./poduri

run-p2:
	./adrese

run-p3:
	./lego

run-p4:
	./retea

clean:
	rm -f poduri adrese lego retea

