# Buzera Tiberiu <tiberiu.buzera@stud.acs.upb.ro>

build:
	g++ crypto.cpp -o crypto
	g++ ridge.cpp -o ridge
	g++ stocks.cpp -o stocks
	g++ trigigel.cpp -o trigigel
	g++ valley.cpp -o valley

run-p1:
	./crypto

run-p2:
	./stocks

run-p3:
	./valley

run-p4:
	./ridge

run-p5:
	./trigigel

clean:
	rm -f crypto ridge stocks trigigel valley

